
import React from 'react';
import { Vehicle, LedgerAccount, Bilty, VehicleDocument } from '../types';
import { Truck, User as UserIcon, MapPin, ArrowRight, Wallet, Receipt, ShieldCheck, Phone, Calendar, AlertTriangle, CheckCircle2, FileText, IndianRupee } from 'lucide-react';
import { getDaysRemaining, getStatusColor } from '../utils/helpers';

// --- SHARED COMPONENTS ---

const ReceiptContainer: React.FC<{ children: React.ReactNode; id: string; title: string }> = ({ children, id, title }) => {
    return (
        // FIXED WIDTH: 300px (Thermal Printer Size) - Fits comfortably on all mobile screens (320px+) without cutting
        <div id={id} className="bg-white font-sans text-slate-900 mx-auto" style={{ width: '300px', flexShrink: 0 }}>
            {/* Header Strip - Compact */}
            <div className="bg-slate-900 p-3 flex justify-between items-center">
                <div className="flex items-center gap-2">
                    <div className="bg-indigo-600 p-1 rounded-md">
                        <Truck size={14} className="text-white" />
                    </div>
                    <div>
                        <h3 className="text-white font-black uppercase text-xs tracking-wide leading-none">FleetDost</h3>
                        <p className="text-slate-400 text-[8px] font-bold tracking-widest mt-0.5">{title}</p>
                    </div>
                </div>
                <div className="text-right">
                    <p className="text-slate-400 text-[7px] font-bold uppercase tracking-widest">Date</p>
                    <p className="text-white text-[9px] font-bold">{new Date().toLocaleDateString('en-IN')}</p>
                </div>
            </div>

            {/* Content Body - Reduced Padding */}
            <div className="p-4 bg-white">
                {children}
            </div>

            {/* Footer */}
            <div className="bg-slate-50 p-2 border-t border-slate-100 flex justify-center items-center gap-1.5">
                <ShieldCheck size={10} className="text-indigo-600" />
                <p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest">Securely Generated by FleetDost</p>
            </div>
        </div>
    );
};

// --- VEHICLE RECEIPT ---
export const VehicleReceipt: React.FC<{ vehicle: Vehicle; id: string; expiryDays: number }> = ({ vehicle, id, expiryDays }) => {
    const docs = vehicle?.documents ? (Object.values(vehicle.documents) as VehicleDocument[]) : [];
    const sortedDocs = docs.sort((a, b) => getDaysRemaining(a?.expiryDate || '') - getDaysRemaining(b?.expiryDate || ''));
    
    // Status Logic
    const expiredCount = sortedDocs.filter(d => d && getDaysRemaining(d.expiryDate) <= 0).length;
    const warningCount = sortedDocs.filter(d => { if (!d) return false; const days = getDaysRemaining(d.expiryDate); return days > 0 && days <= expiryDays; }).length;
    
    let statusBadge = "SAFE";
    let statusColor = "bg-emerald-100 text-emerald-700";
    if (expiredCount > 0) { statusBadge = "EXPIRED"; statusColor = "bg-red-100 text-red-700"; }
    else if (warningCount > 0) { statusBadge = "ATTENTION"; statusColor = "bg-amber-100 text-amber-700"; }

    return (
        <ReceiptContainer id={id} title="VEHICLE REPORT">
            <div className="flex justify-between items-start mb-4 border-b border-slate-100 pb-3">
                <div>
                    <p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest mb-0.5">Vehicle Number</p>
                    <h1 className="text-xl font-black text-slate-900 uppercase tracking-tight">{vehicle?.number || 'UNKNOWN'}</h1>
                    <p className="text-[9px] font-bold text-slate-600 mt-0.5 uppercase flex items-center gap-1">
                        <UserIcon size={9}/> {vehicle?.ownerName || 'N/A'}
                    </p>
                </div>
                <div className={`px-2 py-1 rounded-md ${statusColor}`}>
                    <p className="text-[8px] font-black uppercase tracking-widest">{statusBadge}</p>
                </div>
            </div>

            <div className="space-y-2">
                {sortedDocs.slice(0, 8).map((d: any, i) => {
                    if (!d) return null;
                    const days = getDaysRemaining(d.expiryDate);
                    const status = getStatusColor(d.expiryDate, expiryDays);
                    
                    let icon = <CheckCircle2 size={12} className="text-emerald-500" />;
                    let textColor = "text-slate-700";
                    let dateColor = "text-slate-900";
                    let statusText = `${days}d Left`;

                    if (status === 'red') {
                        icon = <AlertTriangle size={12} className="text-red-500" />;
                        textColor = "text-red-600 font-bold";
                        dateColor = "text-red-600 font-bold";
                        statusText = "EXPIRED";
                    } else if (status === 'yellow') {
                        icon = <AlertTriangle size={12} className="text-amber-500" />;
                        textColor = "text-amber-600 font-bold";
                        dateColor = "text-amber-600";
                        statusText = "Soon";
                    }

                    return (
                        <div key={i} className="flex justify-between items-center bg-slate-50 p-2 rounded-lg border border-slate-100">
                            <div className="flex items-center gap-2">
                                {icon}
                                <span className={`text-[10px] font-bold uppercase ${textColor}`}>{d.name}</span>
                            </div>
                            <div className="text-right">
                                <p className={`text-[11px] font-bold font-mono ${dateColor}`}>{d.expiryDate || '-'}</p>
                                <p className="text-[7px] font-bold text-slate-400 uppercase">{statusText}</p>
                            </div>
                        </div>
                    );
                })}
            </div>
        </ReceiptContainer>
    );
};

// --- LEDGER RECEIPT ---
export const LedgerReceipt: React.FC<{ account: LedgerAccount; id: string }> = ({ account, id }) => {
    const isReceivable = (account?.balance || 0) > 0;
    const amount = Math.abs(account?.balance || 0);
    
    return (
        <ReceiptContainer id={id} title="ACCOUNT STATEMENT">
            <div className="text-center py-3 border-b border-slate-100 mb-3">
                <div className="w-12 h-12 bg-slate-100 rounded-full flex items-center justify-center mx-auto mb-2 text-slate-500">
                    <UserIcon size={24} />
                </div>
                <h2 className="text-lg font-black text-slate-900 uppercase leading-tight px-2">{account?.name}</h2>
                <div className="flex justify-center gap-1.5 mt-1">
                    <span className="text-[8px] bg-slate-100 px-1.5 py-0.5 rounded text-slate-500 font-bold uppercase">{account?.type}</span>
                    {account?.mobile && <span className="text-[8px] bg-slate-100 px-1.5 py-0.5 rounded text-slate-500 font-bold flex items-center gap-1"><Phone size={8}/> {account.mobile}</span>}
                </div>
            </div>

            <div className={`p-4 rounded-xl text-center mb-3 ${isReceivable ? 'bg-emerald-50 border border-emerald-100' : 'bg-red-50 border border-red-100'}`}>
                <p className={`text-[8px] font-black uppercase tracking-widest mb-0.5 ${isReceivable ? 'text-emerald-600' : 'text-red-600'}`}>
                    {isReceivable ? 'NET RECEIVABLE' : 'NET PAYABLE'}
                </p>
                <h1 className={`text-3xl font-black tracking-tighter ${isReceivable ? 'text-emerald-700' : 'text-red-700'}`}>
                    ₹{amount.toLocaleString()}
                </h1>
            </div>

            <div className="bg-slate-50 p-3 rounded-xl text-center">
                <p className="text-[8px] text-slate-400 font-bold uppercase mb-0.5">Last Updated</p>
                <p className="text-[10px] font-bold text-slate-700">{new Date(account?.lastUpdated).toLocaleString()}</p>
            </div>
        </ReceiptContainer>
    );
};

// --- BILTY RECEIPT ---
export const BiltyReceipt: React.FC<{ bilty: Bilty; id: string }> = ({ bilty, id }) => {
    return (
        <ReceiptContainer id={id} title="LORRY RECEIPT (LR)">
            <div className="flex justify-between items-center mb-4 border-b border-slate-200 pb-3">
                <div>
                    <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest">LR Number</p>
                    <h2 className="text-lg font-black text-slate-900">#{bilty?.biltyNumber}</h2>
                </div>
                <div className="text-right">
                    <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest">Date</p>
                    <p className="text-xs font-bold text-slate-900">{bilty?.date}</p>
                </div>
            </div>

            <div className="bg-slate-100 p-2.5 rounded-lg flex justify-between items-center mb-3">
                <div>
                    <p className="text-[7px] font-bold text-slate-500 uppercase">Vehicle</p>
                    <p className="text-xs font-black text-slate-900 uppercase">{bilty?.vehicleNumber}</p>
                </div>
                <div className="text-right">
                    <p className="text-[7px] font-bold text-slate-500 uppercase">Driver</p>
                    <p className="text-[10px] font-bold text-slate-900 uppercase">{bilty?.driverName || '-'}</p>
                </div>
            </div>

            <div className="flex items-center gap-2 mb-4">
                <div className="flex-1 border border-slate-200 p-1.5 rounded-lg">
                    <p className="text-[7px] font-black text-slate-400 uppercase">From</p>
                    <p className="text-[10px] font-bold text-slate-800 uppercase truncate">{bilty?.fromStation}</p>
                </div>
                <ArrowRight size={12} className="text-slate-300" />
                <div className="flex-1 border border-slate-200 p-1.5 rounded-lg">
                    <p className="text-[7px] font-black text-slate-400 uppercase">To</p>
                    <p className="text-[10px] font-bold text-slate-800 uppercase truncate">{bilty?.toStation}</p>
                </div>
            </div>

            <div className="space-y-1.5 mb-3 text-[10px] border-b border-slate-100 pb-3">
                <div className="flex justify-between">
                    <span className="font-bold text-slate-500">Consignor:</span>
                    <span className="font-bold text-slate-900 uppercase truncate max-w-[150px]">{bilty?.consignor?.name}</span>
                </div>
                <div className="flex justify-between">
                    <span className="font-bold text-slate-500">Consignee:</span>
                    <span className="font-bold text-slate-900 uppercase truncate max-w-[150px]">{bilty?.consignee?.name}</span>
                </div>
            </div>

            <div className="border border-slate-200 rounded-lg overflow-hidden mb-3">
                <div className="bg-slate-50 px-2 py-1.5 flex justify-between text-[8px] font-black text-slate-500 uppercase">
                    <span>Item</span>
                    <span>Weight</span>
                </div>
                <div className="px-2 py-1.5 flex justify-between text-[10px] font-bold text-slate-900">
                    <span>{bilty?.itemDetails?.description} ({bilty?.itemDetails?.packages} Pkgs)</span>
                    <span>{bilty?.itemDetails?.weight}</span>
                </div>
            </div>

            <div className="space-y-1">
                <div className="flex justify-between text-[10px]">
                    <span className="font-bold text-slate-500">Total Freight</span>
                    <span className="font-bold text-slate-900">₹{((bilty?.freight?.amount||0) + (bilty?.freight?.labour||0) + (bilty?.freight?.otherCh||0)).toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-[10px]">
                    <span className="font-bold text-emerald-600">Less Advance</span>
                    <span className="font-bold text-emerald-600">- ₹{(bilty?.freight?.advance || 0).toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-xs pt-1.5 border-t border-slate-900 mt-1.5">
                    <span className="font-black text-slate-900 uppercase">Balance Due</span>
                    <span className="font-black text-slate-900">₹{((bilty?.freight?.balance) || 0).toLocaleString()}</span>
                </div>
            </div>
        </ReceiptContainer>
    );
};
